<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Razin-Anik" name="Negative data set" tests="1" failures="1" timestamp="12 Jul 2020 17:26:13 GMT" time="18.816" errors="0">
  <testcase name="validateSignupData" time="5.53" classname="ngScripts.yahooSignupDataDriven">
    <failure type="java.lang.AssertionError" message="expected [yahoo12] but found [Yahoo]">
      <![CDATA[java.lang.AssertionError: expected [yahoo12] but found [Yahoo]
	at ngScripts.yahooSignupDataDriven.validateSignupData(yahooSignupDataDriven.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- validateSignupData -->
</testsuite> <!-- Negative data set -->
